---
- name: Deploy docker-socket-proxy service
  community.docker.docker_container:
    image: "{{ svc_socketproxy_container_image }}"
    pull: "{{ svc_force_pull or svc_socketproxy_version == 'latest' }}"
    name: "{{ svc_socketproxy_container_hostname }}"
    hostname: "{{ svc_socketproxy_container_hostname }}"
    restart_policy: "{{ svc_socketproxy_restart_policy | default(svc_restart_policy) }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env: "{{ socket_proxy_settings | combine(svc_socketproxy_env_vars_baseline) }}"
    memory: "{{ svc_socketproxy_container_memory | default('1g') }}"
    log_driver: "{{ svc_log_driver }}"
    log_options: "{{ svc_log_options }}"
    labels:
      com.centurylinklabs.watchtower.enable: "false"
    networks:
      - name: "{{ svc_socketproxy_network_name }}"
...
