---
- name: Ensure svc_directory is present
  ansible.builtin.file:
    path: "{{ svc_directory_path }}"
    state: directory
    owner: "{{ svc_directory_owner }}"
    group: "{{ svc_directory_group }}"
    mode: "{{ svc_directory_mode }}"
...
