---
- name: Ensure svc_hostnet macvlan network is present
  community.docker.docker_network:
    name: svc_hostnet
    state: present
    driver: macvlan

- name: "Ensure docker bridge network is present ('{{ svc_docker_network_name }}')"
  community.docker.docker_network:
    name: "{{ svc_docker_network_name }}"
    state: present
    driver: bridge
...
