---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - 'main.yml'
      paths:
        - 'vars'

# Gather user facts
- name: Include 'user_facts' tasks
  ansible.builtin.import_tasks: user_facts.yml

# Manage directories
- name: Include 'directories' tasks
  ansible.builtin.import_tasks: directories.yml
  when: svc_manage_directories

# Manage packages
- name: Include 'packages' tasks
  ansible.builtin.import_tasks: packages.yml
  when: svc_manage_packages

# Manage docker networks
- name: Include 'docker_network' tasks
  ansible.builtin.import_tasks: docker_network.yml
  when: svc_manage_docker_networks

# Manage traefik deployment
- name: Include 'traefik' tasks
  ansible.builtin.import_tasks: deploy_traefik.yml
  when: svc_use_traefik

...
