---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - 'vars'

# Gather user facts
- name: Include 'user_facts' tasks
  ansible.builtin.import_tasks: user_facts.yml

# Manage directories
- name: Include 'directories' tasks
  ansible.builtin.import_tasks: directories.yml
  when: svc_manage_directories

# Manage packages
- name: Include 'packages' tasks
  ansible.builtin.import_tasks: packages.yml
  when: svc_manage_packages

# Manage access control
- name: Include 'access_control' tasks
  ansible.builtin.import_tasks: set_access_control.yml

# Manage docker networks
- name: Include 'docker networks' tasks
  ansible.builtin.import_tasks: deploy_networks.yml
  when: svc_manage_docker_networks

# Manage traefik deployment
- name: Include 'traefik' tasks
  ansible.builtin.import_tasks: deploy_traefik.yml
  when: svc_use_traefik

# Manage docker-volume-backup deployment
- name: Include 'docker-volume-backup' tasks
  ansible.builtin.import_tasks: deploy_docker-volume-backup.yml
  when: svc_use_docker_volume_backup

...
