---
- name: Converge
  hosts: all
  become: true

  vars:
    svc_user_name: 1000
    svc_group_name: 1000
    svc_user_uid: 1000
    svc_group_gid: 1000
    svc_traefik_automatic_https: false

  pre_tasks:
    - name: Update package repository cache
      block:
        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 600
          when: ansible_os_family == 'Debian'

        - name: Update pacman cache
          community.general.pacman:
            update_cache: true
            cache_valid_time: 600
          when: ansible_os_family == 'Archlinux'

    - name: Wait for systemd to complete initialization   # noqa command-instead-of-module
      ansible.builtin.command:
        cmd: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Install Python dependencies
      block:
        - name: Install from apt
          ansible.builtin.apt:
            name: python3-requests
            state: present
            install_recommends: false
          when: ansible_os_family == 'Debian'

        - name: Install from pacman
          community.general.pacman:
            name: "{{ svc_packages }}"
            state: python-requests
          when: ansible_os_family == 'Archlinux'

  roles:
    - role: geerlingguy.docker
    - role: netr0m.svc
